### ISSUE TITLE
Using deda_create_dots on a PDF changes the length of the page

### ISSUE THREAD

**Issue by PetSven** [dfd-tud/deda#15]
When I use create_dots on a PDF file the length of the page increase from 11 to 12 inches. It writes the dots on a separate area on top of the page instead of incorporating them into the document. This means the documents I am printing will be a different size, and will not take up the full page. Is this how it is supposed to work?

**Comment by timojuez** [comment]
Hi Peter, what do you mean by “separate area“? Can you please upload a
masked PDF? The dots shall cover the whole page. If you leave the DIN-A4
setting and print in the letter format, there shall be a small (!) border.


Am Do., 12. Sept. 2019 um 17:37 Uhr schrieb Peter Svendsen <
notifications@github.com>:

**Comment by PetSven** [comment]
Here is the output:
[new_dots.pdf](https://github.com/dfd-tud/deda/files/3631592/new_dots.pdf)

The input was an 11 by 8.5 printout of the calibration page. There was no blank white area at the the top of the input page (i.e. the tracking squares were nearer to the top corners).

**Comment by timojuez** [comment]
Hi Peter,

the tool is supposed to anonymise prints. It only works on white areas. In
our tests, non-white areas did not contain tracking dots. So if you print
the new_dots.pdf, there shall be not additional yellow dots on the scanned
image, only on the top of the page.
If you want to remove the dots from a scan, check out the command
deda_clean_document.

I hope this answers your question :)


Am Do., 19. Sept. 2019 um 16:06 Uhr schrieb Peter Svendsen <
notifications@github.com>:
