### ISSUE TITLE
Clarification of the documentation?

### ISSUE THREAD

**Issue by l-g** [dfd-tud/deda#18]
_Optional requirement by deda_anonmask_apply (GNU/Linux only): $ pip3 install wand_

1. Is wand not required on Mac OS X?
2. Don't you need to be root to install wand like that or shouldn't it be installed with _--user_ ?

**Comment by timojuez** [comment]
Hi,

Wand is never being required. If you can mange to install it (whatever
platform), the anonymisation dots can be placed under black areas such as
black text, so they do not overlay them.
Can you install wand with pip3 without the --user parameter? It should be
set automatically when you run pip3 as a user.


Am Sa., 23. Nov. 2019 um 13:39 Uhr schrieb l-g <notifications@github.com>:

**Comment by l-g** [comment]
1. Maybe you should elaborate a bit on what wand is in the documentation. I don't understand it from the context. Isn't it required if you have _light coloured parts_ on your printout?

2. Nope:

```
% pip3 install wand
Collecting wand
  Using cached https://files.pythonhosted.org/packages/3e/43/0fbca3a034c92f3ac989948a0920d0b4f6c0c3c3317769fcaac8dde57e35/Wand-0.5.7-py2.py3-none-any.whl
Installing collected packages: wand
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/3.7'
Consider using the `--user` option or check the permissions.

You are using pip version 19.0.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

This is on Mac OS X 10.15 using Python 3.7 from Mac Ports.

**Comment by timojuez** [comment]
Updated in dev branch.
