### ISSUE TITLE
Cross-referencing in ReadMe

### ISSUE THREAD

**Issue by DonaldTsang** [dfd-tud/deda#19]
Any comments on https://github.com/iandennismiller/yellowdot ?

**Comment by timojuez** [comment]
What does it do? According to the ReadMe, it adds dots randomly. If dots are being distributed randomly, this does not obfuscate the information. If dots are being distributed randomly exactly over the valid places in the cells, the information is distorted but can be repaired by the repetition code. The parity codes can detect distortion in every code word repetition. There are even codes (Pattern 2) where we do not know if there is an inner code with error correcting features so even in this case DEDA adds a dot on all possible places that belong to the code word to obfuscate information.
Maybe the referenced program does something else?

**Comment by DonaldTsang** [comment]
@timojuez I think yellowdot is a worse but respected attempt in trying what deda does
