### ISSUE TITLE
known exceptions

### ISSUE THREAD

**Issue by ukos-git** [dfd-tud/deda#21]
I have a Samsung printer (CLP 320) and it does not seem to produce yd. Is there a list of known limitations of the script?

# steps taken

I have printed the `calibration.pdf`, scanned that in 600dpi color to pnm, converted to losless tiff and analyzed using deda. I could drop the raw scan somewhere, if you are interested in analysing it.

```
▶ deda_extract_yd scan/SnapScanLossless00001.tiff                      
No tracking dot pattern found :-) (0.000001 yellow dots per inch)
```
then the script fails with stack trace
```
Traceback (most recent call last):
  File "/home/matthias/.local/bin/deda_extract_yd", line 10, in <module>
    sys.exit(main())
  File "/home/matthias/.local/lib/python3.7/site-packages/libdeda/extract_yd.py", line 888, in <lambda>
    main = lambda: Main()()
  File "/home/matthias/.local/lib/python3.7/site-packages/libdeda/extract_yd.py", line 91, in __call__
    noCrop=self.args.no_crop)
  File "/home/matthias/.local/lib/python3.7/site-packages/libdeda/extract_yd.py", line 846, in __init__
    self.cleanDotPositions(rotation=not noRotation,crop=not noCrop)
  File "/home/matthias/.local/lib/python3.7/site-packages/libdeda/extract_yd.py", line 673, in cleanDotPositions
    self.rotation = -self.getAngle(self.dots)
AttributeError: 'YellowDotsXposer' object has no attribute 'dots'
```

**Comment by timojuez** [comment]
Hi Matthias,

mainly the printers do not produce yellow tracking dots if they are not
being made in Japan or USA. This is the case for your printer. You can also
check whether the scanner uses some threshold for the white paper and
accidently removes the dots.

Am Mo., 20. Jan. 2020 um 16:04 Uhr schrieb matthias <
notifications@github.com>:

**Comment by ukos-git** [comment]
Thank you. That is viable information. Should that be added to the Readme.md?

**Comment by timojuez** [comment]
Thank you. The second info is somewhere in the Readme under “troubleshooting” and the first info is only true for all printers I know. But I have not analysed all South Korean printers ;)
