### ISSUE TITLE
Unable to find tracking dots - Fuji XEROX

### ISSUE THREAD

**Issue by Claamelee1998** [dfd-tud/deda#24]
Hi,

Thanks for this open source code. However I have an issue: i have multiple samples (more than 10) of FUJI xerox prints with tracking dots clear enough to be seen via simple image processing software, but for all these samples the program said 'no tracking dots found'. I scanned at 300dpi and tried both with auto-exposure and without (no corrections). I also tried enhancing the dots in imageJ but it does not work still. Can you help me? Thanks so much!

**Comment by FritzscheAnita** [comment]
Hello, can you please upload an example?

**Comment by timojuez** [comment]
Please reopen when you provide an example. The reason could be the definition of the range of "yellow" in variable YELLOW in extract_yd.py (hardcoded in source code unfortunately).
