### ISSUE TITLE
RuntimeWarning: invalid value encountered in scalar divide

### ISSUE THREAD

**Issue by martin3000** [dfd-tud/deda#32]
.local/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

ret is 0.0, rcount is 0

Called from libdeda/print_parser.py", line 157, in _get_dxy
dx = np.average((coords[0]-x)%p.d_i)

**Comment by timojuez** [comment]
Danke für den Report. I have not managed to reproduce this. Can you please give the full stack trace or show the command and the input file?

**Comment by martin3000** [comment]
Sorry no, too long ago. I already forgot.
Just avoid dividing by zero.
